version: '3.8'

services:
  nodejs-service:
    container_name: simple-nodejs-container
    build: 
      context: .
    image: tkarnigt/simple-nodejs-api
    ports:
      - "3001:3001"
  nginx:
    container_name: simple-nginx-container
    build:
      context: .
      dockerfile: Dockerfile.nginx
    image: tkarnigt/simple-nginx
    ports:
      - "80:80"
    depends_on:
      - nodejs-service
